/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.consensys.ethclient.launcher;

import static org.junit.Assert.*;

import org.junit.Test;

public class LibraryTest {
  @Test
  public void testSomeLibraryMethod() {
    assertTrue("someLibraryMethod should return 'true'", true);
  }
}
