/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.consensys.ethclient.launcher;

public class Library {
  public boolean someLibraryMethod() {
    return true;
  }
}
